---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "thoth-ci-pipeline-run-pvc"
  labels:
    app: thoth-ci
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
