apiVersion: v1
kind: Template
metadata:
  name: thoth-secret
  annotations:
    description: Thoth secret setup
    openshift.io/display-name: Thoth secret
    version: 0.1.0
  labels:
    template: thoth-secret
    app: thoth-ci

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: github-secret
      labels:
        app: thoth-ci
    stringData:
      webhooksecret: ${WEBHOOK_SECRET}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: auth-secret
      labels:
        app: thoth-ci
    stringData:
      token: ${GIT_TOKEN}

parameters:
  - description: Github webhook secret key.
    displayName: github webhook secret key
    required: true
    name: WEBHOOK_SECRET

  - description: Github oauth token for releases.
    displayName: github oauth token
    required: true
    name: GIT_TOKEN
