apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: action-check
spec:
  params:
    - name: event_action
      type: string
  resources:
    - name: pr
      type: pullRequest
    - name: s2i-thoth
      type: image
  check:
    image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(resources.inputs.s2i-thoth.url) in ocp4.x
    workingDir: /workspace/repo
    securityContext:
      privileged: true
    script: |
      ACTION="opened reopened synchronize created"
      echo $(params.event_action)
      if echo $ACTION | grep -w $(params.event_action) > /dev/null; then
          exit 0
      else
          exit 1
      fi
