apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: retest-comment-check
spec:
  params:
    - name: pr_comment
      type: string
    - name: pr_comment_author_association
      type: string
  resources:
    - name: ubi
      type: image
  check:
    image: $(resources.inputs.ubi.url)
    securityContext:
      privileged: true
    script: |
      author="$(params.pr_comment_author_association)"
      if [ "$author" == "OWNER" ]; then
        if [ "$(params.pr_comment)" == "/approve" ]; then
            exit 0
        else
            exit 1
        fi
      fi
