apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: approve-comment-check
spec:
  params:
    - name: pr_comment
      type: string
    - name: pr_comment_author
      type: string
    - name: pr_comment_author_association
      type: string
  resources:
    - name: ubi
      type: image
    - name: repo
      type: git
  check:
    image: $(resources.inputs.ubi.url)
    securityContext:
      privileged: true
    workingDir: /workspace/repo
    script: |
      author="$(params.pr_comment_author)"
      if [ "$(params.pr_comment)" == "/approve" ]; then
        if grep -qF "@$author" .github/CODEOWNERS ;then
            exit 0
        fi
      fi
      exit 1
