apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: deploy-comment-check
spec:
  params:
    - name: pr_comment
      type: string
    - name: pr_comment_author_association
      type: string
  resources:
    - name: ubi
      type: image
  check:
    image: $(resources.inputs.ubi.url)
    securityContext:
      privileged: true
    script: |
      author_association="$(params.pr_comment_author_association)"
      if ! { [ "$author_association" != "OWNER" -o "$author_association" != "MEMBER" ]; }; then
          echo "Skipping PR, author is not an OWNER or MEMBER: $author"
          exit 1
      fi

      if [ "$(params.pr_comment)" == "/deploy" ]; then
          exit 0
      else
          exit 1
      fi
