apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: overlays-set
spec:
  resources:
    - name: repo
      type: git
    - name: ubi
      type: image
  check:
    image: quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.14.3
    workingDir: /workspace/repo
    script: |
      #!/usr/libexec/platform-python
      import yaml
      import os

      if os.path.isfile('.aicoe-ci.yaml'):
          print("Configuration file available")
          with open(".aicoe-ci.yaml", "r") as stream:
              conf = yaml.safe_load(stream)

          if "overlays-build" in conf.get("check"):
              exit(1)
          else:
              exit(0)
      else:
        print("Configuration file available")
        exit(1)
