apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: pytest-check
spec:
  resources:
    - name: repo
      type: git
  check:
    image: mikefarah/yq:3.3.1
    workingDir: /workspace/repo
    script: |
      if [[ ! -f .aicoe-ci.yaml ]]; then
        exit 0
      else
        check_list=$(yq r -j .aicoe-ci.yaml check)
        out=$(echo "$check_list" | grep -w "thoth-pytest")
        exit_code=$?
        if [[ $exit_code -ne 0 ]]; then
          exit 1
        else
          exit 0
        fi
      fi
