apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: tag-deploy-check
spec:
  params:
    - name: git_ref
      description: Git reference value.
    - name: git_ref_type
      description: Type of ref Tag or Branch.
    - name: repo_name
      description: The git repository title.
    - name: BASE_REPO
      description: Base repository on quay.
      default: "thoth-station"
    - name: CONFIG_REPO
      description: Base repository on quay.
      default: "thoth-application"

  resources:
    - name: ubi
      type: image
  check:
    image: $(resources.inputs.ubi.url)
    securityContext:
      privileged: true
    script: |
      STATUS=$(curl -s -o /dev/null -w '%{http_code}' "https://api.github.com/repos/$(params.BASE_REPO)/$(params.CONFIG_REPO)")
      if [ $STATUS -eq 200 -a "$(params.git_ref_type)" == "tag" ]; then
          exit 0
      else
          exit 1
      fi
