apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: upload-pypi-check
spec:
  resources:
    - name: repo
      type: git
    - name: ubi
      type: image
  check:
    image: quay.io/harshad16/yq:latest
    workingDir: /workspace/repo
    script: |
      if [[ -f setup.py ]]; then
        if [[ ! -f .aicoe-ci.yaml ]]; then
          exit 0
        else
          release_list=$(yq r -j .aicoe-ci.yaml release)
          out=$(echo "$release_list" | grep -w "upload-pypi-sesheta")
          exit_code=$?
          exit $exit_code
        fi
      else
          exit 1
      fi
