apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: aicoe-ci
  app.kubernetes.io/component: tekton
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - conditions/action-check.yaml
  - conditions/config-check.yaml
  - conditions/custom-pipeline-check.yaml
  - conditions/deploy-comment-check.yaml
  - conditions/deployment-check.yaml
  - conditions/issue-check.yaml
  - conditions/retest-comment-check.yaml
  - conditions/sibling-check.yaml
  - conditions/upload-pypi-check.yaml
  - tasks/configuration-task.yaml
  - tasks/custom-pipeline.yaml
  - tasks/init-task.yaml
  - tasks/issue-pypi-release-task.yaml
  - tasks/issue-release-task.yaml
  - tasks/pr-build-release.yaml
  - tasks/pr-build.yaml
  - tasks/pr-config.yaml
  - tasks/pr-merge.yaml
  - tasks/pre-commit-check.yaml
  - tasks/pre-commit-py38-check.yaml
  - tasks/pytest-checks.yaml
  - tasks/pytest-py38-checks.yaml
  - tasks/repo-upstream-sync.yaml
  - tasks/resource.yaml
  - tasks/status-task.yaml
  - tasks/tag-check.yaml
  - tasks/tag-deploy-task.yaml
  - tasks/tag-release-task.yaml
  - tasks/tag-sibling.yaml
  - tasks/tox-checks.yaml
  - tasks/upload-pypi.yaml
  - pipeline/issue-pipeline.yaml
  - pipeline/pull-request-pipeline.yaml
  - pipeline/tag-release-pipeline.yaml
  - trigger/eventlistener.yaml
  - trigger/git-issue-comment-binding.yaml
  - trigger/git-issue-binding.yaml
  - trigger/git-pr-binding.yaml
  - trigger/git-tag-binding.yaml
  - trigger/webhook-tag-binding.yaml
  - triggertemplate/git-issue-template.yaml
  - triggertemplate/git-pr-template.yaml
  - triggertemplate/git-tag-template.yaml
