kind: Secret
apiVersion: v1
metadata:
    name: ultrahook
data:
    api.key: ENC[AES256_GCM,data:PXciPs+Rpp1j+QZK9Xung/0kn5tzBh3sFPQJCnFcpGuhtypPDc8AVJAjVFI=,iv:rqONRaMyOGwN+ebGcLGCo2/Tn4c6kvnqPEFpRq2d9Uk=,tag:LyGCbn+ShUN+jfBk0lg+Kg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/aicoe-thoth-ops/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-15T08:39:00Z'
        enc: CiQAusOmTEC/rkHNyaYcFN/YqWuaO/FPD8/mIbT39DNQDTKGKjoSSQB7Bk+7XCb8iZI6lLmtjtMxpNrBRQChSQg8ITqV/oWrKJyNvJ67oxoHWFu4fU4GfP6rV/jeLUt1ZFKz4Tr6IQLxRiFAzx0aofQ=
    azure_kv: []
    lastmodified: '2020-04-15T08:39:01Z'
    mac: ENC[AES256_GCM,data:l6NBVtEdrSneC5M6HbydoinO3krG94f/vlzPXPjypxUrn/0SLnNHcJrfd80ZqkNJ7SkOM17Qftki+gSas5faHGZ8IWAVLvq2JHwLeaQBwiqe6gCuDil0igUF3mnRyuC3qore6W9zTu5oRILA8GtfUbHYWuh7ZL5xrpz4DWbeeY0=,iv:6vG1v/pb7nUL9vcDB65+eYnrDEHeLhta518GaRokKIo=,tag:Z4jej8RddJ6hDNoqFCpjcw==,type:str]
    pgp:
    -   created_at: '2020-04-15T08:39:00Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAayE1YgESeByoU3vzGFYpYQo1jjyzCe1HazIWWSV2durc
            mMn08WpY/y/zz5zlL+O2ligUNyfHgxLOqwwAojI4MX5MhAQ0puOUG9lBC5JVcuLa
            MM/xHqQHFgt2KQN9ebIJGPnfLnO/7koHv5AbNKtiG3ykLW1j33CmphbSNOfRnmYG
            +/aVAl+Ia27laCTz+xbHmV00IaDCCQXlUntcvlKFBrlAmNZo0dPL4H41A5l74YNp
            ve1UG5F0hdGyVYqXJyc7VU9S7jfrTksj9JZiPrJ80eS9zxNSf0vB796+PkpNKDiA
            3nWr72E5RxY4mm9TbwEXLFmPggtO8zBeWt71zmAjyr07TSJXDq/jlF/culNDSbaI
            M7TyBE65ZS2BmSGBZvkMiV8VXNg8c0eJzlZxdRQjlVvXfMV67RxtkdH/ijc5yMNG
            adEDGqNZPkICfZftD8YZ39o5AKyg9E6qcBsIGXVXmyJF5a8nSIe25jhDnlx7d0Tp
            PRBCDkuFNKvw1o9NxYt7kcomsPx8J+AQQNlXZVbBZ1Z1RjnPdQrOlw622OXECcly
            eEyNeSmv7Osz+MlNVxrgSMfatcYDmRYpMH77jxSAutT/xPJJc+AL5P2ssvkglvY8
            SzAktnCFAwv+SMbb9B3PAXMO5RQ08YrhMk8HTFP1odk+d1BdGaflA1LMZIAnmpnS
            4AHk//mCX0IPocs3JY2Jve/lpuEdsOCF4B3hMLDgTuI4FL3m4JnlexGJ2OhEOPQr
            OzYXOiGMvCqdM643hdklX0QkCpx8HtXgJuShi++V3Uq/f1QW3mvl+iRT4p+xky/h
            fGMA
            =+mQM
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2020-04-15T08:39:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf8CoJASQjuTkaiSs9bNlFTrFWpLfALWFCHTE4SPAmzr4hC
            p8bkukM09ULQB5ZT5WVyxZhbvkYbF0C6ToLef9GO+TboVlwXFp6hs1BeU/kfCRLl
            R77cZeS0OJ9kVemzT3oTTwC3HkZv81aK0u3R0FK5K1KpdaEjq1VsSdBoQAABq781
            QFz/OKz222k2qVbh3sZKNlnIr4XDB3PPCLu6+KaaLwXv6+tGBTYs2KwtusOzhXJK
            RKjYkl+pnrdkOuB/Ti+MC4oQafd+xfeVbrqB7IS9wo7BRDVjZoEs2kZggD0saEaF
            juFFI6gDspJRR4kVTcj2h2EATORvLL6fZga4UrRY5NJeAd0BYVoo1mxrY/mKWjvv
            dmxgtgcniKHIXcEhGCMKyaO5Qopfhhdmkf+FHLSkYdxoCLm0AUJCcJyPLeZepHyR
            +Q6awvtV1AeTT8t6HlK+FxSyOtg4iBEcQatUOoA8pw==
            =DyiB
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
kind: Secret
apiVersion: v1
metadata:
    name: auth-secret
data:
    token: ENC[AES256_GCM,data:P13Hhlap2w2yH1D72ePo0pFkiX2CAgvZ7W1nbaKYlWl2h0u7WiNgBI+VrUtPgjeAsESGOBh//g4=,iv:KMj2A2LzFZC/Z5oJk5tzgUGhvwV63Z7wlbROwYVsINs=,tag:z387vIyMbVLWExmj9p9hWg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/aicoe-thoth-ops/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-15T08:39:00Z'
        enc: CiQAusOmTEC/rkHNyaYcFN/YqWuaO/FPD8/mIbT39DNQDTKGKjoSSQB7Bk+7XCb8iZI6lLmtjtMxpNrBRQChSQg8ITqV/oWrKJyNvJ67oxoHWFu4fU4GfP6rV/jeLUt1ZFKz4Tr6IQLxRiFAzx0aofQ=
    azure_kv: []
    lastmodified: '2020-04-15T08:39:01Z'
    mac: ENC[AES256_GCM,data:l6NBVtEdrSneC5M6HbydoinO3krG94f/vlzPXPjypxUrn/0SLnNHcJrfd80ZqkNJ7SkOM17Qftki+gSas5faHGZ8IWAVLvq2JHwLeaQBwiqe6gCuDil0igUF3mnRyuC3qore6W9zTu5oRILA8GtfUbHYWuh7ZL5xrpz4DWbeeY0=,iv:6vG1v/pb7nUL9vcDB65+eYnrDEHeLhta518GaRokKIo=,tag:Z4jej8RddJ6hDNoqFCpjcw==,type:str]
    pgp:
    -   created_at: '2020-04-15T08:39:00Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAayE1YgESeByoU3vzGFYpYQo1jjyzCe1HazIWWSV2durc
            mMn08WpY/y/zz5zlL+O2ligUNyfHgxLOqwwAojI4MX5MhAQ0puOUG9lBC5JVcuLa
            MM/xHqQHFgt2KQN9ebIJGPnfLnO/7koHv5AbNKtiG3ykLW1j33CmphbSNOfRnmYG
            +/aVAl+Ia27laCTz+xbHmV00IaDCCQXlUntcvlKFBrlAmNZo0dPL4H41A5l74YNp
            ve1UG5F0hdGyVYqXJyc7VU9S7jfrTksj9JZiPrJ80eS9zxNSf0vB796+PkpNKDiA
            3nWr72E5RxY4mm9TbwEXLFmPggtO8zBeWt71zmAjyr07TSJXDq/jlF/culNDSbaI
            M7TyBE65ZS2BmSGBZvkMiV8VXNg8c0eJzlZxdRQjlVvXfMV67RxtkdH/ijc5yMNG
            adEDGqNZPkICfZftD8YZ39o5AKyg9E6qcBsIGXVXmyJF5a8nSIe25jhDnlx7d0Tp
            PRBCDkuFNKvw1o9NxYt7kcomsPx8J+AQQNlXZVbBZ1Z1RjnPdQrOlw622OXECcly
            eEyNeSmv7Osz+MlNVxrgSMfatcYDmRYpMH77jxSAutT/xPJJc+AL5P2ssvkglvY8
            SzAktnCFAwv+SMbb9B3PAXMO5RQ08YrhMk8HTFP1odk+d1BdGaflA1LMZIAnmpnS
            4AHk//mCX0IPocs3JY2Jve/lpuEdsOCF4B3hMLDgTuI4FL3m4JnlexGJ2OhEOPQr
            OzYXOiGMvCqdM643hdklX0QkCpx8HtXgJuShi++V3Uq/f1QW3mvl+iRT4p+xky/h
            fGMA
            =+mQM
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2020-04-15T08:39:00Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf8CoJASQjuTkaiSs9bNlFTrFWpLfALWFCHTE4SPAmzr4hC
            p8bkukM09ULQB5ZT5WVyxZhbvkYbF0C6ToLef9GO+TboVlwXFp6hs1BeU/kfCRLl
            R77cZeS0OJ9kVemzT3oTTwC3HkZv81aK0u3R0FK5K1KpdaEjq1VsSdBoQAABq781
            QFz/OKz222k2qVbh3sZKNlnIr4XDB3PPCLu6+KaaLwXv6+tGBTYs2KwtusOzhXJK
            RKjYkl+pnrdkOuB/Ti+MC4oQafd+xfeVbrqB7IS9wo7BRDVjZoEs2kZggD0saEaF
            juFFI6gDspJRR4kVTcj2h2EATORvLL6fZga4UrRY5NJeAd0BYVoo1mxrY/mKWjvv
            dmxgtgcniKHIXcEhGCMKyaO5Qopfhhdmkf+FHLSkYdxoCLm0AUJCcJyPLeZepHyR
            +Q6awvtV1AeTT8t6HlK+FxSyOtg4iBEcQatUOoA8pw==
            =DyiB
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
