kind: Secret
apiVersion: v1
metadata:
    name: ultrahook
data:
    api.key: ENC[AES256_GCM,data:iq6mog3wf65fYp+PvDRRA8lbJg0uG2IXm+flKTfD7f5jlAZlCJmGXvRZYVQ=,iv:XtxYbhlm00BJyYZKTMJo/uZk2eRrhOquGNl7ppJkyn4=,tag:ggZc7C0cNHsf6XNayEpApA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/aicoe-thoth-ops/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-18T11:34:08Z'
        enc: CiQAusOmTMZTybjBzjBCv/pNaLzVu6r6PbNLW/+qrca6qXuXdrQSSQB7Bk+7+zJkje3jI6BXyD3wv4TY90HthhnVfEiHfGsdcTwVBclg0iLMNDiq1RQ/Ol1t0TBPT+/ONDp78M3cUW04hgs9DKQgd4Q=
    azure_kv: []
    lastmodified: '2020-04-18T11:34:09Z'
    mac: ENC[AES256_GCM,data:Y8LlmydxHci73aG16K11dl7ZjZfxy47Oqn1F5fp9fXYY0R6RWHTsyiaNNyHSMsUu9qHQKzeZylBHl10IH618/yt8QQdNseIaLHP8IaLKoV7SzhMcslQ9IJ4y5LokaJ9SJH8cHmxt+Es6VRwauDb63a0S2tdaepszMHbg3X6H19A=,iv:T6uDav/iBeBX9Neei262Ma0eTC546v8b6xv5PKQ6CAo=,tag:0ogqQZdqZwFLZa8AKQgYIw==,type:str]
    pgp:
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAMHivb96OnQVw9MHj4l2iHmWkbgZJkWOI1Jtj4UZenXNu
            QUE+D8xsmQQ3wb7V1mANLvDFdWYVhalPhyK9LCvYYnu8sTfEWRmsXfLgr3CyQgFP
            dlH8tWY9SGpRr4V2A70wOKpANLi44057C66KwQngN1FG6mC6h6qrZlkhYSsYvh4p
            6MydwzYEtGIe/D3n7k8xSexuEXyn7zNHK0Bvuqj4Y0OsxDIuOm8+YNXmrco6J6Qs
            FVsoBuHWvlT7XhlszhZljWUYdMzVOx+SW6OYlFtDSzKvalg5pldbG0OIL8S55LES
            GqmcTXrxQMuVIlVmHWK7nfwCddhX/XuHbZR+xX/TnGo8Gps+e+XzjQTfLWecx+eQ
            yM1T7S9hu8M0L6/qoUhwVETLJABuEl8SrDdVmCVI9WJhuzfQpe8yIkRTvZgCCofa
            y2pXljnPL4bcjgy2GLvEJS/KR/ORhjJfGDJlxUqi6IzKEyPFVXocrngZyzM7KcUf
            R2G3x6HpRjsgT3jQPujKoVIFNljkR4BxISjbGQFpny3LgSAU80TmIGuvlMgKEsxY
            fEJXU2l8Xo6nAst6YNtuwYjAKBK3nVSe1Dl4Vlpjf+wh6oOEgFuNTiFqr9b3plT/
            8hIGdY0M2HV6Z96sR4V8034lbZBzZTiAPJ4rTOOUDzQJ52OJ9U85AxEER9siSyLS
            4AHkZXui0KIL3C+SMakFYfLLYuFK8eB34A7hKiDg2OLlwb9Z4NTlWN47CPwEogiA
            Bgw4IePrD3YzG67RzzjcAPFy2l5As2vgqORTEjtAC904IeFL0ftm4o5e4o/mZ1Dh
            ys8A
            =27CV
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/YD1nI6aszpS1RDo9UfChEqpQ9gk1vx/CIseWiXU95lo8
            vVtKwVOSElLpu3l1RijWP2bS3zdTzraAgwcxF8E5kY8KTMpMqmKZRcwdKdLY643V
            tAfEYSEoWCh9KgGO1W/9UQGe7WBVczybzKU2Ns1vnHqRMJ5jw8+20z6U2Y5tgCHa
            SiwvtYwAQFCLNVrTAQytNX+3lEDhpkKu8enDrHBxMV1cQ5PgUOMW1jTxP6DDD25Q
            KUIE0ivWOVZL2K6ZfqQcoK431Bkuv49pi+xItVCik15KJTkhgKe63o6IQFlfLw8n
            Jo5kBJbp6ZRCRZiis/ghhiBIAl6BLvpDPaICFiNamNJeAelOBg6xBMExgDKSKuj1
            /4sr52x+fcJTy4Tl7Q3+syPCGdke7zGzzyVa4KzpYDO4H3gujoGu0E45iFsoh7Gx
            o516N+Vlw/8FeGdavGpd+4zQ8qFpGNW+Y7drzq5GoA==
            =7lmC
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
kind: Secret
apiVersion: v1
metadata:
    name: auth-secret
data:
    token: ENC[AES256_GCM,data:BB6F1mrfVh0WYa04O7SQdpLFqDvsRfh/XtuDXt49HsOice3LyjaFZXfLBRWkaQxjCoEmypes8lQ=,iv:RBs3DWv/LFHLvcH13sEUJDZ1VoPT2M+6JrbDIM5Psls=,tag:7o0FIviHXYLk8/Ft/SRjXw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/aicoe-thoth-ops/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-18T11:34:08Z'
        enc: CiQAusOmTMZTybjBzjBCv/pNaLzVu6r6PbNLW/+qrca6qXuXdrQSSQB7Bk+7+zJkje3jI6BXyD3wv4TY90HthhnVfEiHfGsdcTwVBclg0iLMNDiq1RQ/Ol1t0TBPT+/ONDp78M3cUW04hgs9DKQgd4Q=
    azure_kv: []
    lastmodified: '2020-04-18T11:34:09Z'
    mac: ENC[AES256_GCM,data:Y8LlmydxHci73aG16K11dl7ZjZfxy47Oqn1F5fp9fXYY0R6RWHTsyiaNNyHSMsUu9qHQKzeZylBHl10IH618/yt8QQdNseIaLHP8IaLKoV7SzhMcslQ9IJ4y5LokaJ9SJH8cHmxt+Es6VRwauDb63a0S2tdaepszMHbg3X6H19A=,iv:T6uDav/iBeBX9Neei262Ma0eTC546v8b6xv5PKQ6CAo=,tag:0ogqQZdqZwFLZa8AKQgYIw==,type:str]
    pgp:
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAMHivb96OnQVw9MHj4l2iHmWkbgZJkWOI1Jtj4UZenXNu
            QUE+D8xsmQQ3wb7V1mANLvDFdWYVhalPhyK9LCvYYnu8sTfEWRmsXfLgr3CyQgFP
            dlH8tWY9SGpRr4V2A70wOKpANLi44057C66KwQngN1FG6mC6h6qrZlkhYSsYvh4p
            6MydwzYEtGIe/D3n7k8xSexuEXyn7zNHK0Bvuqj4Y0OsxDIuOm8+YNXmrco6J6Qs
            FVsoBuHWvlT7XhlszhZljWUYdMzVOx+SW6OYlFtDSzKvalg5pldbG0OIL8S55LES
            GqmcTXrxQMuVIlVmHWK7nfwCddhX/XuHbZR+xX/TnGo8Gps+e+XzjQTfLWecx+eQ
            yM1T7S9hu8M0L6/qoUhwVETLJABuEl8SrDdVmCVI9WJhuzfQpe8yIkRTvZgCCofa
            y2pXljnPL4bcjgy2GLvEJS/KR/ORhjJfGDJlxUqi6IzKEyPFVXocrngZyzM7KcUf
            R2G3x6HpRjsgT3jQPujKoVIFNljkR4BxISjbGQFpny3LgSAU80TmIGuvlMgKEsxY
            fEJXU2l8Xo6nAst6YNtuwYjAKBK3nVSe1Dl4Vlpjf+wh6oOEgFuNTiFqr9b3plT/
            8hIGdY0M2HV6Z96sR4V8034lbZBzZTiAPJ4rTOOUDzQJ52OJ9U85AxEER9siSyLS
            4AHkZXui0KIL3C+SMakFYfLLYuFK8eB34A7hKiDg2OLlwb9Z4NTlWN47CPwEogiA
            Bgw4IePrD3YzG67RzzjcAPFy2l5As2vgqORTEjtAC904IeFL0ftm4o5e4o/mZ1Dh
            ys8A
            =27CV
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/YD1nI6aszpS1RDo9UfChEqpQ9gk1vx/CIseWiXU95lo8
            vVtKwVOSElLpu3l1RijWP2bS3zdTzraAgwcxF8E5kY8KTMpMqmKZRcwdKdLY643V
            tAfEYSEoWCh9KgGO1W/9UQGe7WBVczybzKU2Ns1vnHqRMJ5jw8+20z6U2Y5tgCHa
            SiwvtYwAQFCLNVrTAQytNX+3lEDhpkKu8enDrHBxMV1cQ5PgUOMW1jTxP6DDD25Q
            KUIE0ivWOVZL2K6ZfqQcoK431Bkuv49pi+xItVCik15KJTkhgKe63o6IQFlfLw8n
            Jo5kBJbp6ZRCRZiis/ghhiBIAl6BLvpDPaICFiNamNJeAelOBg6xBMExgDKSKuj1
            /4sr52x+fcJTy4Tl7Q3+syPCGdke7zGzzyVa4KzpYDO4H3gujoGu0E45iFsoh7Gx
            o516N+Vlw/8FeGdavGpd+4zQ8qFpGNW+Y7drzq5GoA==
            =7lmC
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
kind: Secret
apiVersion: v1
metadata:
    name: github-secret
data:
    webhooksecret: ENC[AES256_GCM,data:aMmVaJ7NcUyj4WbiFGIsYwbDS0xvy4qZmnzhYa2N+qNAD2FYQ5hZBr9NZgU=,iv:07eraiuoA4hMnxuakhh7Y/k0W7Enybeo7uRxFjTk0/4=,tag:h3brAmiJVMQd9gBn6AbCYg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/aicoe-thoth-ops/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-18T11:34:08Z'
        enc: CiQAusOmTMZTybjBzjBCv/pNaLzVu6r6PbNLW/+qrca6qXuXdrQSSQB7Bk+7+zJkje3jI6BXyD3wv4TY90HthhnVfEiHfGsdcTwVBclg0iLMNDiq1RQ/Ol1t0TBPT+/ONDp78M3cUW04hgs9DKQgd4Q=
    azure_kv: []
    lastmodified: '2020-04-18T11:34:09Z'
    mac: ENC[AES256_GCM,data:Y8LlmydxHci73aG16K11dl7ZjZfxy47Oqn1F5fp9fXYY0R6RWHTsyiaNNyHSMsUu9qHQKzeZylBHl10IH618/yt8QQdNseIaLHP8IaLKoV7SzhMcslQ9IJ4y5LokaJ9SJH8cHmxt+Es6VRwauDb63a0S2tdaepszMHbg3X6H19A=,iv:T6uDav/iBeBX9Neei262Ma0eTC546v8b6xv5PKQ6CAo=,tag:0ogqQZdqZwFLZa8AKQgYIw==,type:str]
    pgp:
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAMHivb96OnQVw9MHj4l2iHmWkbgZJkWOI1Jtj4UZenXNu
            QUE+D8xsmQQ3wb7V1mANLvDFdWYVhalPhyK9LCvYYnu8sTfEWRmsXfLgr3CyQgFP
            dlH8tWY9SGpRr4V2A70wOKpANLi44057C66KwQngN1FG6mC6h6qrZlkhYSsYvh4p
            6MydwzYEtGIe/D3n7k8xSexuEXyn7zNHK0Bvuqj4Y0OsxDIuOm8+YNXmrco6J6Qs
            FVsoBuHWvlT7XhlszhZljWUYdMzVOx+SW6OYlFtDSzKvalg5pldbG0OIL8S55LES
            GqmcTXrxQMuVIlVmHWK7nfwCddhX/XuHbZR+xX/TnGo8Gps+e+XzjQTfLWecx+eQ
            yM1T7S9hu8M0L6/qoUhwVETLJABuEl8SrDdVmCVI9WJhuzfQpe8yIkRTvZgCCofa
            y2pXljnPL4bcjgy2GLvEJS/KR/ORhjJfGDJlxUqi6IzKEyPFVXocrngZyzM7KcUf
            R2G3x6HpRjsgT3jQPujKoVIFNljkR4BxISjbGQFpny3LgSAU80TmIGuvlMgKEsxY
            fEJXU2l8Xo6nAst6YNtuwYjAKBK3nVSe1Dl4Vlpjf+wh6oOEgFuNTiFqr9b3plT/
            8hIGdY0M2HV6Z96sR4V8034lbZBzZTiAPJ4rTOOUDzQJ52OJ9U85AxEER9siSyLS
            4AHkZXui0KIL3C+SMakFYfLLYuFK8eB34A7hKiDg2OLlwb9Z4NTlWN47CPwEogiA
            Bgw4IePrD3YzG67RzzjcAPFy2l5As2vgqORTEjtAC904IeFL0ftm4o5e4o/mZ1Dh
            ys8A
            =27CV
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/YD1nI6aszpS1RDo9UfChEqpQ9gk1vx/CIseWiXU95lo8
            vVtKwVOSElLpu3l1RijWP2bS3zdTzraAgwcxF8E5kY8KTMpMqmKZRcwdKdLY643V
            tAfEYSEoWCh9KgGO1W/9UQGe7WBVczybzKU2Ns1vnHqRMJ5jw8+20z6U2Y5tgCHa
            SiwvtYwAQFCLNVrTAQytNX+3lEDhpkKu8enDrHBxMV1cQ5PgUOMW1jTxP6DDD25Q
            KUIE0ivWOVZL2K6ZfqQcoK431Bkuv49pi+xItVCik15KJTkhgKe63o6IQFlfLw8n
            Jo5kBJbp6ZRCRZiis/ghhiBIAl6BLvpDPaICFiNamNJeAelOBg6xBMExgDKSKuj1
            /4sr52x+fcJTy4Tl7Q3+syPCGdke7zGzzyVa4KzpYDO4H3gujoGu0E45iFsoh7Gx
            o516N+Vlw/8FeGdavGpd+4zQ8qFpGNW+Y7drzq5GoA==
            =7lmC
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
---
apiVersion: v1
data:
    thoth-devops: ENC[AES256_GCM,data:Rfkzshrk6txTSgc8AQZCXtsI7uP6/8dI2zGxHKc7SLf7ywpL/u7UmXRZIP0KwSc5rRmptpmPY/PixyoCYIFVzFyUg83btRsIhYDZXnrwWPt5LgVDLrDBpRoQFSu2navOOlAaUr/jGpBdVv8pLJ/wGwY5m1QkE+sJplZmsHDgH+L/XT/wxboItgwogbX4CP4QF41aPpdsKZOiCXf/1jf5erTZUqxethKHzONI95hF42t+ll7wN9HrqFeP25RsNVkaQN+ltI2JinN611Xw,iv:vhln5hWQ//d+ukQawZrnbQGuOl6qggqCbdJtqVNZXqY=,tag:OuvdJeyZ6d0mno1kOcz/YQ==,type:str]
kind: Secret
metadata:
    name: chat-notification
type: Opaque
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/aicoe-thoth-ops/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-18T11:34:08Z'
        enc: CiQAusOmTMZTybjBzjBCv/pNaLzVu6r6PbNLW/+qrca6qXuXdrQSSQB7Bk+7+zJkje3jI6BXyD3wv4TY90HthhnVfEiHfGsdcTwVBclg0iLMNDiq1RQ/Ol1t0TBPT+/ONDp78M3cUW04hgs9DKQgd4Q=
    azure_kv: []
    lastmodified: '2020-04-18T11:34:09Z'
    mac: ENC[AES256_GCM,data:Y8LlmydxHci73aG16K11dl7ZjZfxy47Oqn1F5fp9fXYY0R6RWHTsyiaNNyHSMsUu9qHQKzeZylBHl10IH618/yt8QQdNseIaLHP8IaLKoV7SzhMcslQ9IJ4y5LokaJ9SJH8cHmxt+Es6VRwauDb63a0S2tdaepszMHbg3X6H19A=,iv:T6uDav/iBeBX9Neei262Ma0eTC546v8b6xv5PKQ6CAo=,tag:0ogqQZdqZwFLZa8AKQgYIw==,type:str]
    pgp:
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA1gbAjViyxWYARAAMHivb96OnQVw9MHj4l2iHmWkbgZJkWOI1Jtj4UZenXNu
            QUE+D8xsmQQ3wb7V1mANLvDFdWYVhalPhyK9LCvYYnu8sTfEWRmsXfLgr3CyQgFP
            dlH8tWY9SGpRr4V2A70wOKpANLi44057C66KwQngN1FG6mC6h6qrZlkhYSsYvh4p
            6MydwzYEtGIe/D3n7k8xSexuEXyn7zNHK0Bvuqj4Y0OsxDIuOm8+YNXmrco6J6Qs
            FVsoBuHWvlT7XhlszhZljWUYdMzVOx+SW6OYlFtDSzKvalg5pldbG0OIL8S55LES
            GqmcTXrxQMuVIlVmHWK7nfwCddhX/XuHbZR+xX/TnGo8Gps+e+XzjQTfLWecx+eQ
            yM1T7S9hu8M0L6/qoUhwVETLJABuEl8SrDdVmCVI9WJhuzfQpe8yIkRTvZgCCofa
            y2pXljnPL4bcjgy2GLvEJS/KR/ORhjJfGDJlxUqi6IzKEyPFVXocrngZyzM7KcUf
            R2G3x6HpRjsgT3jQPujKoVIFNljkR4BxISjbGQFpny3LgSAU80TmIGuvlMgKEsxY
            fEJXU2l8Xo6nAst6YNtuwYjAKBK3nVSe1Dl4Vlpjf+wh6oOEgFuNTiFqr9b3plT/
            8hIGdY0M2HV6Z96sR4V8034lbZBzZTiAPJ4rTOOUDzQJ52OJ9U85AxEER9siSyLS
            4AHkZXui0KIL3C+SMakFYfLLYuFK8eB34A7hKiDg2OLlwb9Z4NTlWN47CPwEogiA
            Bgw4IePrD3YzG67RzzjcAPFy2l5As2vgqORTEjtAC904IeFL0ftm4o5e4o/mZ1Dh
            ys8A
            =27CV
            -----END PGP MESSAGE-----
        fp: 34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34
    -   created_at: '2020-04-18T11:34:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA+/WpawS9RPbAQf/YD1nI6aszpS1RDo9UfChEqpQ9gk1vx/CIseWiXU95lo8
            vVtKwVOSElLpu3l1RijWP2bS3zdTzraAgwcxF8E5kY8KTMpMqmKZRcwdKdLY643V
            tAfEYSEoWCh9KgGO1W/9UQGe7WBVczybzKU2Ns1vnHqRMJ5jw8+20z6U2Y5tgCHa
            SiwvtYwAQFCLNVrTAQytNX+3lEDhpkKu8enDrHBxMV1cQ5PgUOMW1jTxP6DDD25Q
            KUIE0ivWOVZL2K6ZfqQcoK431Bkuv49pi+xItVCik15KJTkhgKe63o6IQFlfLw8n
            Jo5kBJbp6ZRCRZiis/ghhiBIAl6BLvpDPaICFiNamNJeAelOBg6xBMExgDKSKuj1
            /4sr52x+fcJTy4Tl7Q3+syPCGdke7zGzzyVa4KzpYDO4H3gujoGu0E45iFsoh7Gx
            o516N+Vlw/8FeGdavGpd+4zQ8qFpGNW+Y7drzq5GoA==
            =7lmC
            -----END PGP MESSAGE-----
        fp: 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
