apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: issue-close
  labels:
    app: thoth-ci
spec:
  params:
    - name: pr_number
      type: string
    - name: event_action
      type: string
  resources:
    inputs:
      - name: pr
        type: pullRequest
      - name: s2i-thoth
        type: image
      - name: ubi8
        type: image
    outputs:
      - name: pr
        type: pullRequest
  steps:
    - name: items-check
      image: registry.access.redhat.com/ubi8/ubi-minimal # use $(resources.inputs.ubi8.url) in ocp4.x
      script: |
        ls -al

    - name: pr-items-check
      image: registry.access.redhat.com/ubi8/ubi-minimal # use $(resources.inputs.ubi8.url) in ocp4.x
      workingDir: /workspace/pr
      script: |
        ls -al

    - name: close-pr
      image: registry.access.redhat.com/ubi8/ubi-minimal # use $(resources.inputs.ubi8.url) in ocp4.x
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      script: |
        echo $(params.event_action)
        cp -r /workspace/pr/ /workspace/output/
        if [ "$(params.event_action)" == "closed" ]; then
          echo "Thanks for the contribution" > /workspace/output/pr/comments/close
        fi
