apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: coala-check
  labels:
    app: thoth-ci
spec:
  params:
    - name: pr_number
      type: string
  resources:
    inputs:
      - name: s2i-thoth
        type: image
      - name: pr
        type: pullRequest
      - name: repo
        type: git
    outputs:
      - name: pr
        type: pullRequest

  steps:
    - name: git-init-op
      image: $(resources.inputs.s2i-thoth.url)
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      script: |
        cp -r /workspace/pr/ /workspace/output/
        git fetch origin pull/$(params.pr_number)/head:workbranch
        git checkout workbranch

    - name: run-coala
      image: quay.io/thoth-station/thoth-coala:v0.10.2
      resources:
        limits:
          memory: "500Mi"
          cpu: "1"
        requests:
          memory: "500Mi"
          cpu: "1"
      workingDir: /workspace/repo
      script: |
        if [[ -f .coafile ]]; then
          set +e
          out=$(coala --ci 2>&1)
          exit_code=$?
          set -e
          if [[ $exit_code -ne 0 ]]; then
            code="failure"
            description="The coala test failed!"
            # echo "Coala Test failed!" > /workspace/output/pr/comments/new
            # echo "Logs:" >> /workspace/output/pr/comments/new
            # echo $out >> /workspace/output/pr/comments/new
          else
            code="success"
            description="The coala test succeeded!"
          fi
          cat <<EOF > /workspace/output/pr/status/coala.json
          {
            "State": "$code",
            "Target": "http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/",
            "Desc": "$description",
            "Label": "thoth-ci/coala-check"
          }
        EOF
        fi
