apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: example-pr-checks
  labels:
    app: thoth-ci
spec:
  inputs:
    params:
      - name: pr_number
        type: string
    resources:
      - name: s2i-thoth
        type: image
      - name: pr
        type: pullRequest
      - name: repo
        type: git

  steps:
    - name: items-check
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(inputs.resources.s2i-thoth.url) in ocp4.x
      command: ["/bin/bash"]
      args: ['-c', 'ls -al']

    - name: repo-items-recheck
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(inputs.resources.s2i-thoth.url) in ocp4.x
      workingDir: /workspace/repo
      command: ["/bin/bash"]
      args: ['-c', 'ls -al']

    - name: output-items-recheck
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(inputs.resources.s2i-thoth.url) in ocp4.x
      workingDir: /workspace/output
      command: ["/bin/bash"]
      args: ['-c', 'ls -al']

    - name: git-init-op
      resources:
        limits:
          memory: "500Mi"
          cpu: "1"
        requests:
          memory: "500Mi"
          cpu: "1"
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(inputs.resources.s2i-thoth.url) in ocp4.x
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      command: ["/bin/bash"]
      args:
      - -c
      - |
        cp -r /workspace/pr/ /workspace/output/
        git fetch origin pull/$(inputs.params.pr_number)/head:workbranch
        git checkout workbranch

    - name: repo-items-recheck
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest
      workingDir: /workspace/repo
      command: ["/bin/bash"]
      args:
      - -c
      - ls -al
