apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: issue-open
  labels:
    app: thoth-ci
spec:
  inputs:
    params:
      - name: pr_number
        type: string
      - name: event_action
        type: string
    resources:
      - name: pr
        type: pullRequest
      - name: s2i-thoth
        type: image
  outputs:
    resources:
      - name: pr
        type: pullRequest
  steps:
    - name: items-check
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(s2i-thoth.params.url) in ocp4.x
      script: |
        ls -al

    - name: pr-items-check
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(s2i-thoth.params.url) in ocp4.x
      workingDir: /workspace/pr
      script: |
        ls -al

    - name: open-pr
      resources:
      image: quay.io/thoth-station/s2i-thoth-ubi8-py36:latest # use $(s2i-thoth.params.url) in ocp4.x
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      script: |
        echo $(inputs.params.event_action)
        cp -r /workspace/pr/ /workspace/output/
        if [ "$(inputs.params.event_action)" == "opened" ] || [ "$(inputs.params.event_action)" == "reopened" ]; then
          echo "Thanks for Opening the Pull Request" > /workspace/output/pr/comments/open
        fi
