apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pr-merge
spec:
  resources:
    inputs:
      - name: ubi
        type: image
      - name: pr
        type: pullRequest
  steps:
    - name: merge-pr
      env:
        - name: GITHUBTOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: token
      image: $(resources.inputs.ubi.url)
      script: |
        #!/usr/libexec/platform-python
        import json
        import os
        import http.client

        with open("/workspace/pr/pr.json") as f:
            PR_INFO = json.load(f)

        status_url = "/repos/{}/pulls/{}/merge".format(PR_INFO["Base"]["Repo"]["FullName"], PR_INFO["Number"])
        data = {
            "sha": PR_INFO["Head"]["Sha"],
            "merge_method": "merge"
        }

        conn = http.client.HTTPSConnection("api.github.com")
        r = conn.request(
            "PUT",
            status_url,
            body=json.dumps(data),
            headers={
                "User-Agent": "aicoe-ci",
                "Authorization": "Bearer " + os.environ["GITHUBTOKEN"],
            })
        resp = conn.getresponse()
        if not str(resp.status).startswith("2"):
            print("Error: %d" % (resp.status))
            print(resp.read())
        else:
            print(resp.read())
