apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-to-quay
  labels:
    app: thoth-ci
spec:
  resources:
    inputs:
      - name: s2i-thoth
        type: image
      - name: image-base
        type: image
      - name: pr
        type: pullRequest
      - name: repo
        type: git
  params:
    # pull request params
    - name: pr_number
      description: Pull Request number.
    - name: pr_repo
      description: Pull Request repository.
  steps:
    - name: skopeo-copy
      image: quay.io/redhat-emea-ssa-team/skopeo-ubi:latest
      command:
        - skopeo
        - copy
        - --authfile=/pushsecret/.dockerconfigjson
        - --src-tls-verify=false
        - --dest-tls-verify=false
        - docker://$(resources.inputs.image-base.url)/$(params.pr_repo)-$(params.pr_number)
        - docker://quay.io/thoth-station/$(params.pr_repo):$(params.pr_number)  # quay.io/thoth-station this is to be parameterized
      volumeMounts:
        - name: quay-creds
          mountPath: /pushsecret
          readOnly: true

  volumes:
    - name: quay-creds
      secret:
        secretName: thoth-station-thoth-pusher-pull-secret # Name of the secret to be parameterized
