apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: release-git-rebase
spec:
  resources:
    inputs:
      - name: git-source-repository
        type: git
  params:
    - name: upstream-url
      description: URL pointing to upstream repository
    - name: pull-api
      description: pull api url
  steps:
    - name: rebase
      workingDir: /workspace/git-source-repository
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: password
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: username
        - name: GITHUB_EMAIL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: user-email
      image: mrnonz/alpine-git-curl:latest
      script: |
        git config --local user.email "$GITHUB_EMAIL"
        git config --local user.name "$GITHUB_USERNAME"
        git remote add upstream "$(params.upstream-url)"
        git fetch upstream
        git checkout -b branch_rebasing
        git rebase upstream/master
        git push origin branch_rebasing

    - name: pull-request
      workingDir: /workspace/git-source-repository
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: password
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: username
      image: mrnonz/alpine-git-curl:latest
      script: | 
        curl --user "$GITHUB_USERNAME:$GITHUB_TOKEN" -X POST -d '{"title":"tekton-testing", "head": "anishasthana:branch_rebasing", "base": "master" }' $(params.pull-api)
