apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-build
spec:
  params:
    # buildah params
    - name: TLSVERIFY
      default: "false"
      description:
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
    - name: LOGLEVEL
      description: Log level when running the S2I binaryx`x
      default: "0"

    # tag params
    - name: git_ref
      description: Git reference value.
    - name: repo_name
      description: The git repository title.
    - name: registry
      description: Container image registry.
      default: "quay.io"
    - name: registry_org
      description: Name of the registry organization.
      default: "thoth-station"
    - name: registry_project
      description: Name of the project repository.
      default: ""
    - name: registry_secret
      description: Registry image push secret.
      default: "thoth-station-thoth-pusher-secret"
    - name: context_path
      description: The location of the path to run s2i from.
      default: .
    - name: dockerfile
      description: Path to the Dockerfile to build.
      default: Dockerfile

  resources:
    inputs:
      - name: s2i-thoth
        type: image
      - name: repo
        type: git

  steps:
    - name: check-ops
      image: $(resources.inputs.s2i-thoth.url)
      securityContext:
        privileged: true
      script: |
        if [ "$(params.registry)" == "quay.io" ]; then
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' "https://quay.io/api/v1/repository/$(params.registry_org)/$(params.registry_project)")
          if [ $STATUS -eq 200 ]; then
              exit 0
          else
              exit 1
          fi
        else
           exit 0
        fi

    - name: git-init-op
      image: $(resources.inputs.s2i-thoth.url)
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      script: |
        git fetch origin --tags
        git checkout tags/$(params.git_ref) -b workbranch

    - name: build
      image: quay.io/buildah/stable
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      script: |
        buildah bud \
        --tls-verify=$(params.TLSVERIFY) \
        --storage-driver=overlay \
        --layers \
        -f \
        $(params.dockerfile) \
        -t \
        $(params.repo_name)-$(params.git_ref) \
        $(params.context_path)
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers

    - name: push
      image: quay.io/buildah/stable
      script: |
        buildah push \
        --authfile=/pushsecret/.dockerconfigjson \
        --tls-verify=$(params.TLSVERIFY) \
        $(params.repo_name)-$(params.git_ref) \
        docker://$(params.registry)/$(params.registry_org)/$(params.registry_project):$(params.git_ref)
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: quay-creds
          mountPath: /pushsecret/
          readOnly: true

  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: gen-source
      emptyDir: {}
    - name: quay-creds
      secret:
        secretName: $(params.registry_secret)
