apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tag-check
  labels:
    app: aicoe-ci
spec:
  params:
    - name: git_ref_type
      description: Type of ref Tag or Branch.
    - name: pipelinerun_name
      description: pipelinerun associated.
  steps:
    - name: init-ops
      image: quay.io/openshift/origin-cli:latest
      script: |
        if [ "$(params.git_ref_type)" == "tag" ]; then
            exit 0
        else
          oc delete pipelinerun $(params.pipelinerun_name)
        fi
