apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tox-check
  labels:
    app: thoth-ci
spec:
  params:
    - name: pr_number
      description: Pull Request number.
    - name: pipelinerun_name
      description: pipelinerun associated.
  resources:
    inputs:
      - name: s2i-thoth
        type: image
      - name: pr
        type: pullRequest
      - name: repo
        type: git
    outputs:
      - name: pr
        type: pullRequest

  steps:
    - name: git-init-op
      image: $(resources.inputs.s2i-thoth.url)
      workingDir: /workspace/repo
      securityContext:
        privileged: true
      script: |
        cp -r /workspace/pr/ /workspace/output/
        git fetch origin pull/$(params.pr_number)/head:workbranch
        git checkout workbranch

    - name: run-tox
      image: docker.io/frenzymadness/fedora-python-tox:latest
      workingDir: /workspace/repo
      script: |
        if [[ -f tox.ini ]]; then
          set +ex
          out=$(tox 2>&1)
          exit_code=$?
          set -ex
          if [[ $exit_code -ne 0 ]]; then
            code="failure"
            description="The tox test failed!"
            echo "<details>
            <summary>Tox Test failed! Click here</summary>

            \`\`\`
            $out
            \`\`\`
            </details>" > /workspace/output/pr/comments/tox
          else
            code="success"
            description="The tox test succeeded!"
          fi
          cat <<EOF > /workspace/output/pr/status/tox.json
          {
            "State": "$code",
            "Target": "http://tekton-dashboard-tekton-pipelines.apps.thoth01.lab.upshift.rdu2.redhat.com/#/namespaces/thoth-ci/pipelineruns/$(params.pipelinerun_name)",
            "Desc": "$description",
            "Label": "thoth-ci/tox-check"
          }
        EOF
        fi
