---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: issue-pipeline
  labels:
    app: aicoe-ci
spec:
  params:
    - name: event_action
      type: string
    - name: issue_number
      type: string
    - name: issue_state
      type: string
    - name: issue_title
      type: string
    - name: issue_body
      type: string
    - name: issue_author_association
      type: string
    - name: issue_author
      type: string
    - name: repo_name
      type: string
    - name: repo_full_name
      type: string
    - name: repo_url
      type: string
    - name: pipelinerun_name
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image

  tasks:
    - name: issue-check
      taskRef:
        name: issue-check
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_title
          value: $(params.issue_title)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)

    - name: configuration
      taskRef:
        name: configuration
      resources:
        inputs:
          - name: repo
            resource: git-repo
      runAfter:
        - issue-check

    - name: issue-release-run
      taskRef:
        name: issue-release
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_number
          value: $(params.issue_number)
        - name: issue_state
          value: $(params.issue_state)
        - name: issue_title
          value: $(params.issue_title)
        - name: issue_body
          value: $(params.issue_body)
        - name: issue_author_association
          value: $(params.issue_author_association)
        - name: issue_author
          value: $(params.issue_author)
        - name: repo_name
          value: $(params.repo_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
        - name: repo_url
          value: $(params.repo_url)
        - name: base_image
          value: $(tasks.configuration.results.base-image)
        - name: build_stratergy
          value: $(tasks.configuration.results.build-stratergy)
        - name: build_source_script
          value: $(tasks.configuration.results.build-source-script)
        - name: registry
          value: $(tasks.configuration.results.registry)
        - name: registry_org
          value: $(tasks.configuration.results.registry-org)
        - name: registry_project
          value: $(tasks.configuration.results.registry-project)
        - name: registry_secret
          value: $(tasks.configuration.results.registry-secret)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: ubi
            resource: ubi
      # runAfter:
      #   - issue-check
