---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: issue-pipeline
  labels:
    app: aicoe-ci
spec:
  params:
    - name: event_action
      type: string
    - name: issue_number
      type: string
    - name: issue_state
      type: string
    - name: issue_title
      type: string
    - name: issue_body
      type: string
    - name: issue_author_association
      type: string
    - name: issue_author
      type: string
    - name: repo_name
      type: string
    - name: repo_full_name
      type: string
    - name: repo_url
      type: string
    - name: ssh_url
      type: string
    - name: pipelinerun_name
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image

  tasks:
    - name: configuration
      taskRef:
        name: configuration
      resources:
        inputs:
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth

    - name: issue-release-run
      taskRef:
        name: issue-release
      conditions:
        - conditionRef: issue-check
          params:
            - name: event_action
              value: $(params.event_action)
            - name: issue_title
              value: $(params.issue_title)
            - name: pipelinerun_name
              value: $(params.pipelinerun_name)
            - name: issue_pipeline_title
              value: "Deliver Container Image"
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_number
          value: $(params.issue_number)
        - name: issue_state
          value: $(params.issue_state)
        - name: issue_title
          value: $(params.issue_title)
        - name: issue_body
          value: $(params.issue_body)
        - name: issue_author_association
          value: $(params.issue_author_association)
        - name: issue_author
          value: $(params.issue_author)
        - name: repo_name
          value: $(params.repo_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
        - name: repo_url
          value: $(params.repo_url)
        - name: base_image
          value: $(tasks.configuration.results.base-image)
        - name: build_stratergy
          value: $(tasks.configuration.results.build-stratergy)
        - name: dockerfile_path
          value: $(tasks.configuration.results.dockerfile-path)
        - name: build_source_script
          value: $(tasks.configuration.results.build-source-script)
        - name: registry
          value: $(tasks.configuration.results.registry)
        - name: registry_org
          value: $(tasks.configuration.results.registry-org)
        - name: registry_project
          value: $(tasks.configuration.results.registry-project)
        - name: registry_secret
          value: $(tasks.configuration.results.registry-secret)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: ubi
            resource: ubi

    - name: issue-deploy-run
      taskRef:
        name: issue-deploy
      conditions:
        - conditionRef: deployment-check
          resources:
            - name: repo
              resource: git-repo
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_number
          value: $(params.issue_number)
        - name: issue_state
          value: $(params.issue_state)
        - name: issue_title
          value: $(params.issue_title)
        - name: issue_body
          value: $(params.issue_body)
        - name: issue_author_association
          value: $(params.issue_author_association)
        - name: issue_author
          value: $(params.issue_author)
        - name: repo_name
          value: $(params.repo_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
        - name: repo_url
          value: $(params.repo_url)
        - name: registry
          value: $(tasks.configuration.results.registry)
        - name: registry_org
          value: $(tasks.configuration.results.registry-org)
        - name: registry_project
          value: $(tasks.configuration.results.registry-project)
        - name: deploy_project_org
          value: $(tasks.configuration.results.deploy-project-org)
        - name: deploy_project_name
          value: $(tasks.configuration.results.deploy-project-name)
        - name: deploy_image_name
          value: $(tasks.configuration.results.deploy-image-name)
        - name: overlay_contextpath
          value: $(tasks.configuration.results.overlay-contextpath)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - issue-release-run

    - name: issue-pypi-release-run
      taskRef:
        name: issue-pypi-release
      conditions:
        - conditionRef: issue-check
          params:
            - name: event_action
              value: $(params.event_action)
            - name: issue_title
              value: $(params.issue_title)
            - name: pipelinerun_name
              value: $(params.pipelinerun_name)
            - name: issue_pipeline_title
              value: "Deliver Missing Module"
        - conditionRef: upload-pypi-check
          resources:
            - name: repo
              resource: git-repo
            - name: ubi
              resource: ubi
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_number
          value: $(params.issue_number)
        - name: issue_state
          value: $(params.issue_state)
        - name: issue_title
          value: $(params.issue_title)
        - name: issue_body
          value: $(params.issue_body)
        - name: issue_author_association
          value: $(params.issue_author_association)
        - name: issue_author
          value: $(params.issue_author)
        - name: repo_name
          value: $(params.repo_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
        - name: repo_url
          value: $(params.repo_url)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: ubi
            resource: ubi

    - name: issue-pulp-release-run
      taskRef:
        name: issue-pulp-pypi-release
      conditions:
        - conditionRef: issue-check
          params:
            - name: event_action
              value: $(params.event_action)
            - name: issue_title
              value: $(params.issue_title)
            - name: pipelinerun_name
              value: $(params.pipelinerun_name)
            - name: issue_pipeline_title
              value: "Deliver Missing Module"
        - conditionRef: upload-pulp-pypi-check
          resources:
            - name: repo
              resource: git-repo
            - name: ubi
              resource: ubi
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_number
          value: $(params.issue_number)
        - name: issue_state
          value: $(params.issue_state)
        - name: issue_title
          value: $(params.issue_title)
        - name: issue_body
          value: $(params.issue_body)
        - name: issue_author_association
          value: $(params.issue_author_association)
        - name: issue_author
          value: $(params.issue_author)
        - name: repo_name
          value: $(params.repo_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
        - name: repo_url
          value: $(params.repo_url)
        - name: pulp-index
          value: $(tasks.configuration.results.pulp-index)
        - name: allow-sdist
          value: $(tasks.configuration.results.allow-sdist)
        - name: allow-bdist
          value: $(tasks.configuration.results.allow-bdist)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: ubi
            resource: ubi


    - name: upstream-sync-issue-run
      taskRef:
        name: repo-upstream-sync
      conditions:
        - conditionRef: issue-check
          params:
            - name: event_action
              value: $(params.event_action)
            - name: issue_title
              value: $(params.issue_title)
            - name: pipelinerun_name
              value: $(params.pipelinerun_name)
            - name: issue_pipeline_title
              value: "Upstream Sync Up"
      params:
        - name: event_action
          value: $(params.event_action)
        - name: issue_number
          value: $(params.issue_number)
        - name: issue_state
          value: $(params.issue_state)
        - name: issue_title
          value: $(params.issue_title)
        - name: issue_body
          value: $(params.issue_body)
        - name: issue_author_association
          value: $(params.issue_author_association)
        - name: issue_author
          value: $(params.issue_author)
        - name: repo_name
          value: $(params.repo_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
        - name: repo_url
          value: $(params.repo_url)
        - name: ssh_url
          value: $(params.ssh_url)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: ubi
            resource: ubi
