---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: thoth-ci-pipeline
  labels:
    app: thoth-ci
spec:
  params:
    - name: event_action
      type: string
    - name: pr_number
      type: string
    - name: pr_repo
      type: string
    - name: pr_merged
      type: string
    - name: pr_comment
      type: string
    - name: pr_comment_author
      type: string
    - name: pr_comment_author_association
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: image-base
      type: image-base
    - name: pr-source
      type: pullRequest

  tasks:
    - name: init-task-run
      taskRef:
        name: init-task
      params:
        - name: event_action
          value: $(params.event_action)
        - name: pr_comment
          value: $(params.pr_comment)
        - name: pr_comment_author
          value: $(params.pr_comment_author)
        - name: pr_comment_author_association
          value: $(params.pr_comment_author_association)
        - name: pr_merged
          value: $(params.pr_merged)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: pr
            resource: pr-source
        outputs:
          - name: pr
            resource: pr-source

    - name: coala-run
      taskRef:
        name: coala-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
      params:
        - name: pr_number
          value: $(params.pr_number)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run

    - name: pytest-run
      taskRef:
        name: pytest-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
      params:
        - name: pr_number
          value: $(params.pr_number)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run

    - name: pr-build-run
      taskRef:
        name: pr-s2i-build
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: image-base
            resource: image-base
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run

    - name: pr-build-release-run
      taskRef:
        name: release-to-quay
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
        - conditionRef: deploy-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: s2i-thoth
              resource: s2i-thoth
            - name: pr
              resource: pr-source
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: image-base
            resource: image-base
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
