---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: thoth-ci-pipeline
  labels:
    app: thoth-ci
spec:
  params:
    - name: event_action
      type: string
    - name: pr_number
      type: string
    - name: pr_repo
      type: string
    - name: repo_full_name
      type: string
    - name: pr_merged
      type: string
    - name: pr_comment
      type: string
    - name: pr_comment_author
      type: string
    - name: pr_comment_author_association
      type: string
    - name: pipelinerun_name
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image
    - name: pr-source
      type: pullRequest

  tasks:
    - name: init-task-run
      taskRef:
        name: init-task
      params:
        - name: event_action
          value: $(params.event_action)
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
        - name: pr_comment
          value: $(params.pr_comment)
        - name: pr_comment_author
          value: $(params.pr_comment_author)
        - name: pr_comment_author_association
          value: $(params.pr_comment_author_association)
        - name: pr_merged
          value: $(params.pr_merged)
      resources:
        inputs:
          - name: ubi
            resource: ubi
          - name: pr
            resource: pr-source
        outputs:
          - name: pr
            resource: pr-source

    - name: status-task-run
      taskRef:
        name: status-task
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source

    - name: pre-commit-run
      taskRef:
        name: pre-commit-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: coala-run
      taskRef:
        name: coala-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: pytest-run
      taskRef:
        name: pytest-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: pr-build-run
      taskRef:
        name: pr-s2i-build
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
        outputs:
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: pr-merge-run
      taskRef:
        name: pr-merge
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: approve-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      resources:
        inputs:
          - name: ubi
            resource: ubi
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: pr-build-release-run
      taskRef:
        name: pr-build-release
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: deploy-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: pr-deploy-run
      taskRef:
        name: tag-deploy
      params:
        - name: git_ref
          value: $(params.pr_number)
        - name: repo_name
          value: $(params.pr_repo)
        - name: IMAGESTREAM_PATH
          value: "$(params.pr_repo)/overlays/test/imagestreamtag.yaml"
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - pr-build-release-run
