---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: thoth-ci-pipeline
  labels:
    app: thoth-ci
spec:
  params:
    - name: pr_number
      type: string
    - name: pr_repo
      type: string
    - name: event_action
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: image-base
      type: image-base
    - name: pr-source
      type: pullRequest

  tasks:
    - name: issue-open-run
      taskRef:
        name: issue-open
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: event_action
          value: $(params.event_action)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: pr
            resource: pr-source
        outputs:
          - name: pr
            resource: pr-source

    - name: issue-close-run
      taskRef:
        name: issue-close
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: event_action
          value: $(params.event_action)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: pr
            resource: pr-source
        outputs:
          - name: pr
            resource: pr-source

    - name: coala-run
      taskRef:
        name: coala-check
      params:
        - name: pr_number
          value: $(params.pr_number)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source

    - name: pytest-run
      taskRef:
        name: pytest-check
      params:
        - name: pr_number
          value: $(params.pr_number)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
        outputs:
          - name: pr
            resource: pr-source

    - name: pr-build-run
      taskRef:
        name: pr-s2i-build
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: image-base
            resource: image-base
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
      runAfter:
        - coala-run
        - pytest-run
