---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pull-request-pipeline
  labels:
    app: aicoe-ci
spec:
  params:
    - name: event_action
      type: string
    - name: pr_number
      type: string
    - name: pr_repo
      type: string
    - name: repo_full_name
      type: string
    - name: repo_url
      type: string
    - name: pr_comment
      type: string
    - name: pr_comment_author
      type: string
    - name: pr_comment_author_association
      type: string
    - name: pipelinerun_name
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image
    - name: pr-source
      type: pullRequest

  tasks:
    - name: init-task-run
      taskRef:
        name: init-task
      params:
        - name: event_action
          value: $(params.event_action)
        - name: repo_url
          value: $(params.repo_url)
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
        - name: pr_comment
          value: $(params.pr_comment)
        - name: pr_comment_author
          value: $(params.pr_comment_author)
        - name: pr_comment_author_association
          value: $(params.pr_comment_author_association)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo

    - name: pr-configuration
      taskRef:
        name: pr-config
      params:
        - name: pr_number
          value: $(params.pr_number)
      resources:
        inputs:
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth

    - name: status-task-run
      taskRef:
        name: status-task
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
        - name: repo_full_name
          value: $(params.repo_full_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth

    - name: pre-commit-run
      taskRef:
        name: pre-commit-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: config-check
          params:
            - name: event
              value: "thoth-precommit"
          resources:
            - name: repo
              resource: git-repo
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - init-task-run
        - status-task-run

    - name: pre-commit-py38-run
      taskRef:
        name: pre-commit-py38-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: config-check
          params:
            - name: event
              value: "thoth-precommit-py38"
          resources:
            - name: repo
              resource: git-repo
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - init-task-run
        - status-task-run

    - name: pytest-run
      taskRef:
        name: pytest-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: config-check
          params:
            - name: event
              value: "thoth-pytest"
          resources:
            - name: repo
              resource: git-repo
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
        - name: pytest_env
          value: $(tasks.pr-configuration.results.pytest-env)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - init-task-run
        - status-task-run

    - name: pytest-py38-run
      taskRef:
        name: pytest-py38-check
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: config-check
          params:
            - name: event
              value: "thoth-pytest-py38"
          resources:
            - name: repo
              resource: git-repo
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
        - name: pytest_env
          value: $(tasks.pr-configuration.results.pytest-env)
      resources:
        inputs:
          - name: pr
            resource: pr-source
          - name: repo
            resource: git-repo
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - init-task-run
        - status-task-run

    - name: pr-build-run
      taskRef:
        name: pr-s2i-build
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: config-check
          params:
            - name: event
              value: "thoth-build"
          resources:
            - name: repo
              resource: git-repo
        - conditionRef: retest-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
        - name: pipelinerun_name
          value: $(params.pipelinerun_name)
        - name: base_image
          value: $(tasks.pr-configuration.results.base-image)
        - name: build_stratergy
          value: $(tasks.pr-configuration.results.build-stratergy)
        - name: build_source_script
          value: $(tasks.pr-configuration.results.build-source-script)
        - name: dockerfile_path
          value: $(tasks.pr-configuration.results.dockerfile-path)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run
        - status-task-run

    - name: pr-build-release-run
      taskRef:
        name: pr-build-release
      conditions:
        - conditionRef: action-check
          params:
            - name: event_action
              value: $(params.event_action)
          resources:
            - name: ubi
              resource: ubi
        - conditionRef: deploy-comment-check
          params:
            - name: pr_comment
              value: $(params.pr_comment)
            - name: pr_comment_author_association
              value: $(params.pr_comment_author_association)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: pr_number
          value: $(params.pr_number)
        - name: pr_repo
          value: $(params.pr_repo)
        - name: overlay_name
          value: ""
        - name: base_image
          value: $(tasks.pr-configuration.results.base-image)
        - name: build_stratergy
          value: $(tasks.pr-configuration.results.build-stratergy)
        - name: build_source_script
          value: $(tasks.pr-configuration.results.build-source-script)
        - name: dockerfile_path
          value: $(tasks.pr-configuration.results.dockerfile-path)
        - name: registry
          value: $(tasks.pr-configuration.results.registry)
        - name: registry_org
          value: $(tasks.pr-configuration.results.registry-org)
        - name: registry_project
          value: $(tasks.pr-configuration.results.registry-project)
        - name: registry_secret
          value: $(tasks.pr-configuration.results.registry-secret)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
          - name: pr
            resource: pr-source
      runAfter:
        - init-task-run

    - name: pr-deploy-run
      taskRef:
        name: tag-deploy
      params:
        - name: git_ref
          value: pr-$(params.pr_number)
        - name: repo_name
          value: $(params.pr_repo)
        - name: registry
          value: $(tasks.pr-configuration.results.registry)
        - name: registry_org
          value: $(tasks.pr-configuration.results.registry-org)
        - name: registry_project
          value: $(tasks.pr-configuration.results.registry-project)
        - name: deploy_project_org
          value: $(tasks.pr-configuration.results.deploy-project-org)
        - name: deploy_project_name
          value: $(tasks.pr-configuration.results.deploy-project-name)
        - name: deploy_image_name
          value: $(tasks.pr-configuration.results.deploy-image-name)
        - name: overlay_contextpath
          value: $(tasks.pr-configuration.results.overlay-contextpath)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
      runAfter:
        - pr-build-release-run
