---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tag-release-pipeline
  labels:
    app: thoth-ci
spec:
  params:
    - name: git_ref
      type: string
    - name: git_ref_type
      type: string
    - name: repo_name
      type: string
  resources:
    - name: git-repo
      type: git
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image

  tasks:
    - name: tag-release-run
      taskRef:
        name: tag-release
      conditions:
        - conditionRef: tag-check
          params:
            - name: git_ref
              value: $(params.git_ref)
            - name: git_ref_type
              value: $(params.git_ref_type)
            - name: repo_name
              value: $(params.repo_name)
          resources:
            - name: ubi
              resource: ubi
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: git_ref_type
          value: $(params.git_ref_type)
        - name: repo_name
          value: $(params.repo_name)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
          - name: repo
            resource: git-repo
