---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: z-stream-release-pipeline
  labels:
    app: aicoe-ci
spec:
  params:
    - name: git_ref
      type: string
    - name: repo_url
      type: string
  resources:
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image

  tasks:
    - name: z-stream-release-run
      taskRef:
        name: z-stream-release
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: repo_url
          value: $(params.repo_url)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
