---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: z-stream-release-pipeline
  labels:
    app: aicoe-ci
spec:
  params:
    - name: git_ref
      type: string
    - name: opf_org
      type: string
    - name: opf_repo
      type: string
    - name: opf_repo_url
      type: string
    - name: opf_default_branch
      type: string
  resources:
    - name: s2i-thoth
      type: image
    - name: ubi
      type: image

  tasks:
    - name: z-stream-release-run
      taskRef:
        name: z-stream-release
      params:
        - name: git_ref
          value: $(params.git_ref)
        - name: opf_org
          value: $(params.opf_org)
        - name: opf_repo
          value: $(params.opf_repo)
        - name: opf_repo_url
          value: $(params.opf_repo_url)
        - name: opf_default_branch
          value: $(params.opf_default_branch)
      resources:
        inputs:
          - name: s2i-thoth
            resource: s2i-thoth
