apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: qebhwt-binding
spec:
  params:
  - name: event_action
    value: $(body.action)
  - name: pr_number
    value: $(body.number)
  - name: pr_url
    value: $(body.pull_request.html_url)
  - name: repo_url
    value: $(body.pull_request.head.repo.html_url)
