---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aicoe-ci-webhook-binding
  labels:
    app: aicoe-ci
subjects:
  - kind: ServiceAccount
    name: aicoe-ci-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aicoe-ci-role
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: aicoe-ci-webhook-edit
  labels:
    app: aicoe-ci
subjects:
  - kind: ServiceAccount
    name: aicoe-ci-webhook
roleRef:
  name: edit
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: aicoe-ci-edit
  labels:
    app: aicoe-ci
subjects:
  - kind: ServiceAccount
    name: aicoe-ci
roleRef:
  name: edit
