apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: git-model-template
  labels:
    app: aicoe-ci
spec:
  params:
    - name: pr_number
      description: Pull request ID.
    - name: pr_repo
      description: The git repository pr was raised to.
    - name: pr_url
      description: The pr url.
    - name: repo_url
      description: The git repository url.
    - name: default_branch
      description: The git repository default branch.
    - name: event_action
      description: Action performed on Pull request.
      default: "DEFAULT"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: aicoe-model-pipelinerun-$(uid)
        labels:
          app: aicoe-ci
          project: $(tt.params.pr_repo)
          component: $(tt.params.pr_repo)-pr-$(tt.params.pr_number)
      spec:
        serviceAccountName: aicoe-ci
        pipelineRef:
          name: "gather-deployment-metrics-pipeline"
        params:
          - name: event_action
            value: $(tt.params.event_action)
          - name: pr_number
            value: $(tt.params.pr_number)
          - name: pr_repo
            value: $(tt.params.pr_repo)
          - name: repo_url
            value: $(tt.params.repo_url)
        resources:
          - name: git-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.default_branch)
                - name: url
                  value: $(tt.params.repo_url)
          - name: thoth-s2i-py38
            resourceRef:
              name: thoth-s2i-py38
          - name: pipeline-helpers
            resourceRef:
              name: pipeline-helpers
          - name: thoth-ops
            resourceRef:
              name: thoth-ops
          - name: pr-source
            resourceSpec:
              type: pullRequest
              params:
                - name: url
                  value: $(tt.params.pr_url)
              secrets:
                - fieldName: authToken
                  secretName: auth-secret
                  secretKey: token
