apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: aicoe-ci-listener
  labels:
    app: aicoe-ci
spec:
  serviceAccountName: aicoe-ci-webhook
  triggers:
    - name: github-pull-request
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - pull_request
      bindings:
        - name: git-pr-binding
      template:
        name: git-pr-template

    - name: github-pull-request-comment
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - issue_comment
      bindings:
        - name: git-issue-comment-binding
      template:
        name: git-pr-template

    - name: github-tag-release
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - create
      bindings:
        - name: git-tag-binding
      template:
        name: git-tag-template

    - name: github-issue-release
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - issues
      bindings:
        - name: git-issue-binding
      template:
        name: git-issue-template

    - name: webhook-tag-release
      bindings:
        - name: webhook-tag-binding
      template:
        name: git-tag-template
