apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: aicoe-ci-listener
  labels:
    app: aicoe-ci
spec:
  serviceAccountName: aicoe-ci-webhook
  triggers:
    - name: github-pull-request
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - pull_request
        - cel:
            filter: "body.action in ['opened', 'closed', 'synchronize', 'reopened', 'created']"
      bindings:
        - ref: git-pr-binding
      template:
        ref: git-pr-template

    - name: github-pull-request-comment
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - issue_comment
        - cel:
            filter: "body.comment.body.startsWith('/retest') || body.comment.body.startsWith('/deploy')"
      bindings:
        - ref: git-issue-comment-binding
      template:
        ref: git-pr-template

    - name: github-tag-release
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - create
        - cel:
            filter: "body.ref_type == 'tag'"
      bindings:
        - ref: git-tag-binding
      template:
        ref: git-tag-template

    - name: github-issue-release
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - issues
        - cel:
            filter: "(body.issue.title in ['Deliver Container Image','Deliver Missing Module','Upstream Sync Up']) && (body.action in ['opened', 'reopened'])"
      bindings:
        - ref: git-issue-binding
      template:
        ref: git-issue-template

    # z-stream release pipeline for operate-first
    - name: odh-z-stream-release
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: webhooksecret
            eventTypes:
              - create
        - cel:
            filter: "(body.ref_type == 'tag') && (body.repository.full_name == 'opendatahub-io/odh-manifests')"
      bindings:
        - ref: z-stream-release-binding
      template:
        ref: z-stream-release-template

    - name: webhook-tag-release
      bindings:
        - ref: webhook-tag-binding
      template:
        ref: git-tag-template
