apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: git-issue-template
  labels:
    app: thoth-ci
spec:
  params:
    - name: event_action
      description: Action of Issue.
    - name: issue_number
      description: Issue number.
    - name: issue_state
      description: State of the Issue.
    - name: issue_title
      description: Title of the Issue.
    - name: issue_body
      description: Body of the Issue.
    - name: issue_author_association
      description: Author association of the Issue.
    - name: issue_author
      description: Author of the Issue.
    - name: repo_name
      description: The git repository issue was raised in.
    - name: repo_full_name
      description: The git repository full name.
    - name: repo_url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: $(params.repo_name)-issue-$(params.issue_number)-$(uid)
        labels:
          app: thoth-ci
          component: $(params.repo_name)-issue-$(params.issue_number)
      spec:
        serviceAccountName: thoth-ci
        pipelineRef:
          name: issue-pipeline
        params:
          - name: event_action
            value: $(params.event_action)
          - name: issue_number
            value: $(params.issue_number)
          - name: issue_state
            value: $(params.issue_state)
          - name: issue_title
            value: $(params.issue_title)
          - name: issue_body
            value: $(params.issue_body)
          - name: issue_author_association
            value: $(params.issue_author_association)
          - name: issue_author
            value: $(params.issue_author)
          - name: repo_name
            value: $(params.repo_name)
          - name: repo_full_name
            value: $(params.repo_full_name)
          - name: repo_url
            value: $(params.repo_url)
        resources:
          - name: git-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: master
                - name: url
                  value: $(params.repo_url)
          - name: s2i-thoth
            resourceRef:
              name: thoth-s2i
          - name: ubi
            resourceRef:
              name: ubi8
