apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: webhook-tag-binding
  labels:
    app: thoth-ci
spec:
  params:
  - name: git_ref
    value: $(body.ref)
  - name: git_ref_type
    value: $(body.ref_type)
  - name: repo_name
    value: $(body.repo_name)
  - name: repo_url
    value: $(body.repo_url)
