apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: git-tag-template
  labels:
    app: aicoe-ci
spec:
  params:
    - name: git_ref
      description: Git reference value.
    - name: git_ref_type
      description: Type of ref Tag or Branch.
    - name: repo_name
      description: The git repository title.
    - name: repo_url
      description: The git repository url.
    - name: default_branch
      description: The git repository default branch.
    - name: pipelinerun_name
      description: pipelinerun associated.

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: tag-release-$(uid)
        labels:
          app: aicoe-ci
          project: $(params.repo_name)
          component: tag-$(params.repo_name)
      spec:
        serviceAccountName: aicoe-ci
        timeout: "2h"
        pipelineRef:
          name: tag-release-pipeline
        params:
          - name: git_ref
            value: $(params.git_ref)
          - name: git_ref_type
            value: $(params.git_ref_type)
          - name: repo_name
            value: $(params.repo_name)
          - name: repo_url
            value: $(params.repo_url)
          - name: default_branch
            value: $(params.default_branch)
          - name: uid
            value: $(uid)
          - name: pipelinerun_name
            value: tag-release-$(uid)
        resources:
          - name: git-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.default_branch)
                - name: url
                  value: $(params.repo_url)
          - name: s2i-thoth
            resourceRef:
              name: thoth-s2i
          - name: ubi
            resourceRef:
              name: ubi8
