apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: git-pr-template
  labels:
    app: aicoe-ci
spec:
  params:
    - name: pr_number
      description: Pull request ID.
    - name: pr_repo
      description: The git repository pr was raised to.
    - name: repo_full_name
      description: The git repository full name.
    - name: pr_url
      description: The pr url.
    - name: repo_url
      description: The git repository url.
    - name: ssh_url
      description: The git repository ssh url.
    - name: default_branch
      description: The git repository default branch.
    - name: event_action
      description: Action performed on Pull request.
      default: "DEFAULT"
    - name: pr_comment
      description: comment on the pull request.
      default: "DEFAULT"
    - name: pr_comment_author
      description: author of the comment on the pull request.
      default: "DEFAULT"
    - name: pr_comment_author_association
      description: comment author's association.
      default: "DEFAULT"
    - name: pipelinerun_name
      description: pipelinerun associated.
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: aicoe-pipelinerun-$(uid)
        labels:
          app: aicoe-ci
          project: $(tt.params.pr_repo)
          component: $(tt.params.pr_repo)-pr-$(tt.params.pr_number)
      spec:
        serviceAccountName: aicoe-ci
        pipelineRef:
          name: pull-request-pipeline
        params:
          - name: event_action
            value: $(tt.params.event_action)
          - name: pr_number
            value: $(tt.params.pr_number)
          - name: pr_repo
            value: $(tt.params.pr_repo)
          - name: repo_url
            value: $(tt.params.repo_url)
          - name: ssh_url
            value: $(tt.params.ssh_url)
          - name: default_branch
            value: $(tt.params.default_branch)
          - name: repo_full_name
            value: $(tt.params.repo_full_name)
          - name: pr_comment
            value: $(tt.params.pr_comment)
          - name: pr_comment_author
            value: $(tt.params.pr_comment_author)
          - name: pr_comment_author_association
            value: $(tt.params.pr_comment_author_association)
          - name: pipelinerun_name
            value: aicoe-pipelinerun-$(uid)
        resources:
          - name: git-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.default_branch)
                - name: url
                  value: $(tt.params.repo_url)
          - name: s2i-thoth
            resourceRef:
              name: thoth-s2i
          - name: ubi
            resourceRef:
              name: ubi8
          - name: pr-source
            resourceSpec:
              type: pullRequest
              params:
                - name: url
                  value: $(tt.params.pr_url)
              secrets:
                - fieldName: authToken
                  secretName: auth-secret
                  secretKey: token
