---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ultrahook
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/ultrahook:v0.1.0
      importPolicy: {}
      referencePolicy:
        type: Local
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: ultrahook-aicoe-ci
spec:
  replicas: 1
  selector:
    instance: ultrahook-aicoe-ci
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        instance: ultrahook-aicoe-ci
    spec:
      containers:
        - env:
            - name: ULTRAHOOK_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api.key
                  name: ultrahook
            - name: ULTRAHOOK_SUBDOMAIN
              value: aicoe-ci
            - name: ULTRAHOOK_DESTINATION
              value: http://el-aicoe-ci-listener.aicoe-infra-prod.svc:8080
          image: ultrahook
          imagePullPolicy: Always
          name: ultrahook-aicoe-ci
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 50Mi
  test: false
