---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greg-issue-reciever-binding
subjects:
  - kind: ServiceAccount
    name: greg-issue-reciever-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: greg-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: greg-issue-reciever-edit
subjects:
  - kind: ServiceAccount
    name: greg-issue-reciever-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: greg-issue-edit
subjects:
  - kind: ServiceAccount
    name: greg-issue-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
