apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/Gregory-Pereira/apps.git
    - name: revision
      value: master