---
kind: Secret
apiVersion: v1
metadata:
    name: auth-secret
    annotations:
      tekton.dev/git-0: github.com
data:
    ssh-privatekey: <ssh-privatekey>
    token: <auth-token>
    user-email: <user-email>
    user-name: <user-name>
type: kubernetes.io/ssh-auth
---
kind: Secret
apiVersion: v1
metadata:
    name: github-secret
data:
    webhooksecret: <github-webhook-secret>
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: pypi-secret
data:
    password: <pypi-account-password>
    username: <pypi-account-username>
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
    name: quay-pusher-secret
data:
    .dockerconfigjson: <.dockerconfigjson>
type: kubernetes.io/dockerconfigjson
