apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: aicoe-ci
  app.kubernetes.io/component: tekton
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - ../../../conditions
  - ../../../tasks
  - ../../../pipeline
  - ../../../trigger
  - ../../../triggertemplate
  - binding.yaml
  - role.yaml
  - serviceaccount.yaml
generators:
  - secret-generator.yaml
