---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aicoe-ci-op-role
rules:
  - verbs:
      - get
      - list
      - create
      - watch
      - patch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - limitranges
      - serviceaccounts
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aicoe-ci-op-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aicoe-ci-op-role
subjects:
  - kind: ServiceAccount
    name: tekton-pipelines-controller
    namespace: openshift-pipelines
