apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-aicoe-ci-listener
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-aicoe-ci-listener
    weight: 100
  wildcardPolicy: None
