---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aicoe-ci
  labels:
    app: aicoe-ci
secrets:
  - name: auth-secret
imagePullSecrets:
  - name: thoth-station-thoth-pusher-secret
  - name: aicoe-pusher-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aicoe-ci-webhook
  labels:
    app: aicoe-ci
