---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aicoe-ci
  labels:
    app: aicoe-ci
secrets:
  - name: auth-secret
imagePullSecrets:
  - name: aicoe-pusher-secret
  - name: aicoe-ci-dockercfg-r2v9t
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aicoe-ci-webhook
  labels:
    app: aicoe-ci
