---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aicoe-ci
  labels:
    app: aicoe-ci
secrets:
  - name: auth-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aicoe-ci-webhook
  labels:
    app: aicoe-ci
